services:
  mongo:
    image: mongo:8
    container_name: puryfier-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-puryfi}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-puryfi}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: puryfier-front
    environment:
      - VITE_BACKEND_URL=${BACKEND_URL:-http://localhost:8000}
      - VITE_PURYFI_WS_URL=${WEBSOCKET_URL:-ws://localhost:8000}
      - VITE_APP_VERSION="0.2.0"
    restart: unless-stopped
    ports:
      - "5173:80"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: puryfier-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - CHASTER_DEVELOPER_TOKEN=${CHASTER_DEVELOPER_TOKEN}
      - CHASTER_WEBHOOK_USER=${CHASTER_WEBHOOK_USER}
      - CHASTER_WEBHOOK_PWD=${CHASTER_WEBHOOK_PWD}
      - DATABASE_URL=${DATABASE_URL}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8000}
      - FRONT_URL=${FRONT_URL:-http://localhost:5173}
      - WEBSOCKET_URL=${WEBSOCKET_URL:-ws://localhost:8000}

volumes:
  mongo_data:
